import Head from "next/head";
import styles from "../styles/Home.module.css";
import clsx from "clsx";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ThakHouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={clsx(styles.section, styles.header)}>
        Header or Main Section
      </section>
      <section className={clsx(styles.section, styles.introduction)}>
        Intro
      </section>
      <section className={clsx(styles.section, styles.services)}>
        Services
      </section>
      <section className={clsx(styles.section, styles.faq)}>
        Frequently Asked Questions
      </section>
      <section className={clsx(styles.section, styles.contactus)}>
        Contact Us
      </section>
    </div>
  );
}
