import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ThakHouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="header">Header or Main Section</section>
      <section className="introduction">Intro</section>
      <section className="services">Services</section>
      <section className="faq">Frequently Asked Questions</section>
      <section className="contactus">Contact Us</section>

      <footer className={styles.footer}>
        <p>{new Date().toDateString()}</p>
      </footer>
    </div>
  );
}
